### ISSUE TITLE
変換エラーがでてた

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#699]
```
Traceback (most recent call last):
  File "run.py", line 424, in <module>
    main()
  File "run.py", line 418, in main
    result = Generator().generate('site', paths, all_paths)
  File "run.py", line 359, in generate
    index, metas = self.make_index(md, names, idgen, nojump)
  File "run.py", line 291, in make_index
    type = Generator.identify_type(metas, names, nojump)
  File "run.py", line 286, in identify_type
    raise RuntimeError(f'unexpected meta: {metas}')
RuntimeError: unexpected meta: {'header': ['format'], 'id-type': ['basic_format_arg'], 'namespace': ['std'], 'cpp': ['cpp20']}
```

調べます。

**Comment by faithandbrave** [comment]
直ってるはずなんだけど、なぜかサーバーがgit pullで最新を持ってきてくれない。。。 @melpon

**Comment by melpon** [comment]
うーーん、前もあったんですが、普通に git pull したら更新されるのに、webhook 経由での更新がうまく機能してない（ことがある）みたいなんですよね。とりあえずは更新されたと思います。

**Comment by faithandbrave** [comment]
ありがとうございます。
GitHub Pagesのリポジトリは更新されてますね。ただサイトの方になぜかまだ反映されていないので、反映されたのが確認できたら閉じます。

**Comment by faithandbrave** [comment]
更新されました。
